In [2]:

import pandas as pd

data = {
    "Employee_ID": [101, 102, 103, 104, 104, 105, 106],
    "Name": ["Tanvi", "Rahul", "Priya", "Amit", "Amit", None, "Neha"],
    "Age": [22, 25, None, 28, 28, 24, 27],
    "Salary": ["25000", "30000", "28000", "35000", "35000", "32000", "invalid"],
    "Department": ["IT", "hr", " IT ", "Sales", "Sales", "HR", "it"],
    "Joining_Date": [
        "2024-01-10", "15/02/2024", "2024-03-20",
        "25/04/2024", "25/04/2024", "2024-05-15", "unknown"
    ]
}

df = pd.DataFrame(data)

print("Original Dataset:")
display(df)

Original Dataset:

   Employee_ID   Name   Age   Salary Department Joining_Date
0          101  Tanvi  22.0    25000         IT   2024-01-10
1          102  Rahul  25.0    30000         hr   15/02/2024
2          103  Priya   NaN    28000        IT    2024-03-20
3          104   Amit  28.0    35000      Sales   25/04/2024
4          104   Amit  28.0    35000      Sales   25/04/2024
5          105    NaN  24.0    32000         HR   2024-05-15
6          106   Neha  27.0  invalid         it      unknown

In [3]:

df.to_csv("employee_data_original.csv", index=False)

print("Original dataset saved successfully.")

Original dataset saved successfully.

## Step 1: Identify missing values
Meaning: Missing values are entries where data is not available. In Pandas, they can be represented by NaN or None.

In [4]:

print("Missing Values in Each Column:")
print(df.isnull().sum())

Missing Values in Each Column:
Employee_ID     0
Name            1
Age             1
Salary          0
Department      0
Joining_Date    0
dtype: int64

In [5]:
 #Find the rows containing missing values

missing_rows = df[df.isnull().any(axis=1)]

display(missing_rows)

   Employee_ID   Name   Age Salary Department Joining_Date
2          103  Priya   NaN  28000        IT    2024-03-20
5          105    NaN  24.0  32000         HR   2024-05-15

In [6]:
#Handle missing values

df_clean = df.copy()

median_age = df_clean["Age"].median()

df_clean["Age"] = df_clean["Age"].fillna(median_age)

print("Dataset After Handling Missing Ages:")
display(df_clean)

Dataset After Handling Missing Ages:

   Employee_ID   Name   Age   Salary Department Joining_Date
0          101  Tanvi  22.0    25000         IT   2024-01-10
1          102  Rahul  25.0    30000         hr   15/02/2024
2          103  Priya  26.0    28000        IT    2024-03-20
3          104   Amit  28.0    35000      Sales   25/04/2024
4          104   Amit  28.0    35000      Sales   25/04/2024
5          105    NaN  24.0    32000         HR   2024-05-15
6          106   Neha  27.0  invalid         it      unknown

In [7]:
#After handling the missing age, check the missing-value counts again.
print("Missing Values After Handling:")
print(df_clean.isnull().sum())

Missing Values After Handling:
Employee_ID     0
Name            1
Age             0
Salary          0
Department      0
Joining_Date    0
dtype: int64

## Day 7 — Task 2: Detect and Remove Duplicate Records
Meaning: Duplicate records are rows that repeat data already present in a dataset. Duplicate records can lead to incorrect counts and calculations, so we must identify them before deciding whether to remove them.

## Detect duplicate records
Pandas provides duplicated() to identify duplicate rows.

In [8]:
#Detect duplicate records
print("Duplicate Records:")
print(df_clean.duplicated())
print("______________________")
#Count duplicate records
print("Number of Duplicate Rows:", df_clean.duplicated().sum())

Duplicate Records:
0    False
1    False
2    False
3    False
4     True
5    False
6    False
dtype: bool
______________________
Number of Duplicate Rows: 1

## Display duplicate rows
Before removing anything, inspect the duplicate records.

In [9]:

duplicates = df_clean[df_clean.duplicated()]

display(duplicates)

   Employee_ID  Name   Age Salary Department Joining_Date
4          104  Amit  28.0  35000      Sales   25/04/2024

## Remove duplicate records
Use drop_duplicates() to remove repeated rows.

In [10]:

df_clean = df_clean.drop_duplicates()

print("Dataset After Removing Duplicates:")
display(df_clean)

Dataset After Removing Duplicates:

   Employee_ID   Name   Age   Salary Department Joining_Date
0          101  Tanvi  22.0    25000         IT   2024-01-10
1          102  Rahul  25.0    30000         hr   15/02/2024
2          103  Priya  26.0    28000        IT    2024-03-20
3          104   Amit  28.0    35000      Sales   25/04/2024
5          105    NaN  24.0    32000         HR   2024-05-15
6          106   Neha  27.0  invalid         it      unknown

In [11]:
#Verify the result
print("Duplicate Rows After Cleaning:", df_clean.duplicated().sum())
print("Total Rows After Cleaning:", df_clean.shape[0])

Duplicate Rows After Cleaning: 0
Total Rows After Cleaning: 6

In [12]:
#If you want to check duplicates using only the employee ID:
print(df_clean["Employee_ID"].duplicated().sum())

0

## Day 7 — Task 3: Correct Data Types
Meaning: Correcting data types means converting a column into the appropriate data type so that calculations, comparisons, and analysis work correctly.

### For example, salary values may be stored as text instead of numbers. We need to convert them to a numeric type before calculating total or average salary.

In [13]:
#Check the current data types

print(df_clean.dtypes)

Employee_ID       int64
Name                str
Age             float64
Salary              str
Department          str
Joining_Date        str
dtype: object

## Convert Salary into a numeric type
Use pd.to_numeric() to convert the salary values into numbers.

##### Because our dataset contains "invalid", we will use errors="coerce" to convert values that cannot be parsed into missing values (NaN).

In [14]:

df_clean["Salary"] = pd.to_numeric(
    df_clean["Salary"],
    errors="coerce"
)

print(df_clean[["Name", "Salary"]])
print("\nUpdated Data Type:")
print(df_clean["Salary"].dtype)

    Name   Salary
0  Tanvi  25000.0
1  Rahul  30000.0
2  Priya  28000.0
3   Amit  35000.0
5    NaN  32000.0
6   Neha      NaN

Updated Data Type:
float64

In [15]:
#Identify values that could not be converted
#Since "invalid" was converted into NaN, we should identify the affected row.

print(df_clean[df_clean["Salary"].isnull()])


#This displays the employee record whose salary could not be converted.

   Employee_ID  Name   Age  Salary Department Joining_Date
6          106  Neha  27.0     NaN         it      unknown

In [16]:
#Verify the data type
print(df_clean.dtypes)

#The Salary column should now have a numeric data type.

Employee_ID       int64
Name                str
Age             float64
Salary          float64
Department          str
Joining_Date        str
dtype: object

## Standardize Inconsistent Text Categories
Meaning: Standardizing text categories means making text values consistent by correcting differences in capitalization, extra spaces, or spelling where the correct value is known.

### For example, 
#### "IT", "it", and " IT " represent the same department but are written differently. If we do not standardize them, our analysis may count them as separate categories.

In [17]:
#Identify inconsistent categories :-First, check the unique values in the Department column.
print(df_clean["Department"].unique())

<StringArray>
['IT', 'hr', ' IT ', 'Sales', 'HR', 'it']
Length: 6, dtype: str

In [18]:
#Remove extra spaces :-Use str.strip() to remove spaces at the beginning and end of text values.

df_clean["Department"] = df_clean["Department"].str.strip()
print(df_clean["Department"].unique())

#Now " IT " becomes "IT".

<StringArray>
['IT', 'hr', 'Sales', 'HR', 'it']
Length: 5, dtype: str

In [19]:
#Standardize capitalization :-Use str.upper() to convert all department names to uppercase.
df_clean["Department"] = df_clean["Department"].str.upper()
print(df_clean["Department"].unique())

<StringArray>
['IT', 'HR', 'SALES']
Length: 3, dtype: str

In [20]:
#Verify the cleaned categories :-Check the department names and their counts.
print(df_clean["Department"].value_counts())

#This shows how many records belong to each department.

#Why is value_counts() useful? It helps analysts check category frequencies and confirm that inconsistent spellings are no longer counted separately.

Department
IT       3
HR       2
SALES    1
Name: count, dtype: int64

In [ ]:
#Other useful methods

For this task, you mainly need str.strip() and str.upper(). Two related methods are:

Method	            Purpose	                                               Example
str.lower()    	Converts text to lowercase	                              "IT" → "it"
str.title()	    Capitalizes the first letter of each word           	"human resources" → "Human Resources"

## Convert Date Columns into Proper Datetime Values
Meaning: Date conversion means changing date values stored as text into a proper datetime data type so that we can sort dates, calculate time differences, and analyse data by day, month, or year.

In [21]:
#Check the current data

print(df_clean["Joining_Date"])
print("\nCurrent Data Type:")
print(df_clean["Joining_Date"].dtype)

0    2024-01-10
1    15/02/2024
2    2024-03-20
3    25/04/2024
5    2024-05-15
6       unknown
Name: Joining_Date, dtype: str

Current Data Type:
str

In [22]:
#Convert the column to datetime :-Use pd.to_datetime() to convert the dates.

df_clean["Joining_Date"] = pd.to_datetime(
    df_clean["Joining_Date"],
    format="mixed",
    dayfirst=True,
    errors="coerce"
)

print(df_clean[["Name", "Joining_Date"]])

    Name Joining_Date
0  Tanvi   2024-10-01
1  Rahul   2024-02-15
2  Priya   2024-03-20
3   Amit   2024-04-25
5    NaN   2024-05-15
6   Neha          NaT

In [23]:
#Check the converted data type
print(df_clean["Joining_Date"].dtype)

datetime64[us]

In [24]:
#Identify invalid or missing dates
print(df_clean[df_clean["Joining_Date"].isna()])

   Employee_ID  Name   Age  Salary Department Joining_Date
6          106  Neha  27.0     NaN         IT          NaT

In [25]:
#Use dates for analysis :-Once converted, you can extract the year and month from the date column.
df_clean["Joining_Year"] = df_clean["Joining_Date"].dt.year
df_clean["Joining_Month"] = df_clean["Joining_Date"].dt.month
print(df_clean[["Name", "Joining_Date", "Joining_Year", "Joining_Month"]])

    Name Joining_Date  Joining_Year  Joining_Month
0  Tanvi   2024-10-01        2024.0           10.0
1  Rahul   2024-02-15        2024.0            2.0
2  Priya   2024-03-20        2024.0            3.0
3   Amit   2024-04-25        2024.0            4.0
5    NaN   2024-05-15        2024.0            5.0
6   Neha          NaT           NaN            NaN

## Compare the Dataset Before and After Cleaning
Meaning: Comparing data before and after cleaning means checking the original dataset against the cleaned dataset to verify which problems were fixed and whether the data is ready for analysis.

In [27]:
#Compare the datasets

print("Original Dataset:")
display(df)

print("Cleaned Dataset:")
display(df_clean)

print("______________________________")

#Compare the number of rows and columns
print("Original Shape:", df.shape)
print("Cleaned Shape:", df_clean.shape)

print("______________________________")

#Compare missing values

comparison = pd.DataFrame({
    "Original Missing Values": df.isnull().sum(),
    "Cleaned Missing Values": df_clean.isnull().sum()
})

print(comparison)

print("______________________________")

#Compare data types
comparison_types = pd.DataFrame({   
    "Original Data Types": df.dtypes.astype(str),  
    "Cleaned Data Types": df_clean.dtypes.astype(str)
})
print(comparison_types)

print("______________________________")

#Check duplicates after cleaning
print("Original Duplicate Rows:", df.duplicated().sum())
print("Cleaned Duplicate Rows:", df_clean.duplicated().sum())

print("______________________________")

Original Dataset:

   Employee_ID   Name   Age   Salary Department Joining_Date
0          101  Tanvi  22.0    25000         IT   2024-01-10
1          102  Rahul  25.0    30000         hr   15/02/2024
2          103  Priya   NaN    28000        IT    2024-03-20
3          104   Amit  28.0    35000      Sales   25/04/2024
4          104   Amit  28.0    35000      Sales   25/04/2024
5          105    NaN  24.0    32000         HR   2024-05-15
6          106   Neha  27.0  invalid         it      unknown

Cleaned Dataset:

,Employee_ID,Name,Age,Salary,Department,Joining_Date,Joining_Year,Joining_Month
0,101,Tanvi,22.0,25000.0,IT,2024-10-01,2024.0,10.0
1,102,Rahul,25.0,30000.0,HR,2024-02-15,2024.0,2.0
2,103,Priya,26.0,28000.0,IT,2024-03-20,2024.0,3.0
3,104,Amit,28.0,35000.0,SALES,2024-04-25,2024.0,4.0
5,105,NaN,24.0,32000.0,HR,2024-05-15,2024.0,5.0
6,106,Neha,27.0,NaN,IT,NaT,NaN,NaN

______________________________
Original Shape: (7, 6)
Cleaned Shape: (6, 8)
______________________________
               Original Missing Values  Cleaned Missing Values
Age                                1.0                       0
Department                         0.0                       0
Employee_ID                        0.0                       0
Joining_Date                       0.0                       1
Joining_Month                      NaN                       1
Joining_Year                       NaN                       1
Name                               1.0                       1
Salary                             0.0                       1
______________________________
              Original Data Types Cleaned Data Types
Age                       float64            float64
Department                    str                str
Employee_ID                 int64              int64
Joining_Date                  str     datetime64[us]
Joining_Month                 NaN            float64
Joining_Year                  NaN            float64
Name                          str                str
Salary                        str            float64
______________________________
Original Duplicate Rows: 1
Cleaned Duplicate Rows: 0
______________________________